diffusion_objective:
  _target_: nuplan.planning.training.modeling.objectives.diffusion_objective.DiffusionObjective
  _convert_: 'all'

  weight: 1.0                  # weight contribution to the overall loss
